### ISSUE TITLE
QR code generating in asp.net web page

### ISSUE THREAD

**Issue by emilymar22** [nays12/QRCode-Authentication-Web#6]
https://mssqltutorial01.blogspot.com/2018/06/how-to-generate-and-read-qr-code-in.html

try this link, it shows how to generate on asp.net web page with video

**Comment by nays12** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Event QR Code Generation](https://trello.com/c/aMh4JvS9/17-event-qr-code-generation)

**Comment by ortunomarilin** [comment]
Thanks Emily. This is actually the video I saw to originally be able to show the image on the web app. I actually made a branch yesterday with the code. I tested it and it works. It will show the QR Code on the screen. I don't know if you guys can see because it shows under a fork master. Anyways, it looks like you have to create a file and then retrieve the image by accessing it through the URL of the folder. (I think).

**Comment by emilymar22** [comment]
@ortunomarilin when I was watching the video yes you are correct, you do create a file within the web application and yes put the extension of the URL of the folder in the main web app so when they click the button it will generate on there. From here i think we can get anything resolved. Thanks Marilin !

**Comment by nays12** [comment]
I agree with you both in the regard that Zxing is definitely the library to use! This would be even better than using an API because sending the data to another server and then back would take too much time. I found this pretty good tutorial on ZXing I'm going to try!
https://www.youtube.com/watch?v=wgcHT6Uu_ew

**Comment by nays12** [comment]
I have written some code in the DisplayQR.aspx.cs file that takes some text and generates a QR from it. It then saves it as a jpg in the project and displays it in an image control!
